Repository AY2425S1-CS2103T-T08-4/tp, pull requests merged in 2024-10, with the labels that each got.

#11 Add Dom's photo
  docs/images/dominopizzaaaa.png
Labels: type.Task, priority.High

#32 Add Grade and GradeList class to track student grades
  src/main/java/seedu/address/model/person/Grade.java
  src/main/java/seedu/address/model/person/GradeList.java
Labels: priority.High

#35 Make Grade class immutable and add getters
  src/main/java/seedu/address/model/person/Grade.java
  src/main/java/seedu/address/model/person/GradeList.java
Labels: priority.High

#40 Add AttendanceTest and AttendanceListTest
  src/main/java/seedu/address/model/person/AttendanceList.java
  src/test/java/seedu/address/model/person/AttendanceListTest.java
  src/test/java/seedu/address/model/person/AttendanceTest.java
Labels: priority.High, severity.Medium

#43 Fix equals methods in Attendance and AttendanceList
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/AttendanceList.java
  src/test/java/seedu/address/model/person/AttendanceListTest.java
Labels: priority.Medium

#45 Create add and delete grade commands, connect to UI
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddGradeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGradeCommand.java
  src/main/java/seedu/address/logic/parser/AddGradeCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteGradeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Grade.java
  src/main/java/seedu/address/model/person/GradeList.java
  src/main/java/seedu/address/storage/JsonAdaptedGrade.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/model/person/GradeListTest.java
  src/test/java/seedu/address/model/person/GradeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#63 Update grade command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddGradeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGradeCommand.java
  src/main/java/seedu/address/logic/parser/DeleteGradeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Grade.java
  src/main/java/seedu/address/model/person/GradeList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/DeleteGradeCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteGradeCommandParserTest.java
  src/test/java/seedu/address/model/person/GradeListTest.java
Labels: priority.High

#59 Add UML diagram for adding grades
  docs/addGradeCommand.puml
Labels: priority.Medium

#61 Update User Guide
  docs/UserGuide.md
Labels: priority.High

#74 Handle overall weightage and tests
  build.gradle
  src/main/java/seedu/address/logic/commands/AddGradeCommand.java
  src/main/java/seedu/address/model/person/GradeList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/exceptions/ExceedTotalWeightageException.java
  src/test/java/seedu/address/logic/commands/AddGradeCommandTest.java
  src/test/java/seedu/address/model/person/GradeListTest.java
Labels: priority.High

#76 Add immutability check
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.Medium
