Repository AY2425S1-CS2103T-T08-4/tp, pull requests merged in 2024-11, with the labels that each got.

#106 Add screenshots of output in
  docs/UserGuide.md
  docs/images/AddPerson.png
  docs/images/EditPerson.png
  docs/images/ListPersons.png
  docs/images/StartUpPage.png
  docs/images/addGrade.png
  docs/images/clearMessage.png
  docs/images/deleteGrade.png
  docs/images/deletePerson.png
  docs/images/markAttendance.png
  docs/images/unmarkAttendance.png
Labels: priority.High

#104 Fix weightage calculation bug in addGrade method
  src/main/java/seedu/address/logic/commands/AddGradeCommand.java
  src/main/java/seedu/address/model/person/GradeList.java
Labels: priority.High

#118 Update grade weightage logic to include 0
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Grade.java
Labels: priority.High

#122 Handle Indian name formats
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.High

#131 Grade case insensitive
  src/main/java/seedu/address/logic/parser/AddGradeCommandParser.java
  src/main/java/seedu/address/model/person/GradeList.java
  src/test/java/seedu/address/model/person/GradeListTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High

#119 Enforce weightage to have max of 2 d.p.
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Grade.java
  src/test/java/seedu/address/logic/parser/AddGradeCommandParserTest.java
Labels: priority.High

#121 Enforce max of 2 d.p. for score
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Grade.java
  src/test/java/seedu/address/logic/parser/AddGradeCommandParserTest.java
Labels: priority.Medium

#150 Modify addGrade success message
  src/main/java/seedu/address/logic/commands/AddGradeCommand.java
Labels: alpha-bug

#149 Support case-insensitive aggGrade operations value
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: alpha-bug

#148 Support case-insensitive attendance values
  src/main/java/seedu/address/model/person/Attendance.java
  src/test/java/seedu/address/model/person/AttendanceTest.java
Labels: alpha-bug

#152 Add no attendance records message
  src/main/java/seedu/address/model/person/AttendanceList.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/model/person/AttendanceListTest.java
Labels: alpha-bug

#169 Fix aggGrade reduce operation bug
  src/main/java/seedu/address/logic/commands/AggGradeCommand.java
Labels: priority.High

#173 Change default data tag to more relevant words
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: alpha-bug

#189 Change documentation screenshots
  docs/images/StartUpPage.png
  docs/images/Ui.png
  docs/images/absentees.png
  docs/images/addGrade.png
  docs/images/addPerson.png
  docs/images/aggGrade_filtered.png
  docs/images/aggGrade_normal.png
  docs/images/clearMessage.png
  docs/images/deleteGrade.png
  docs/images/deletePerson.png
  docs/images/editPerson.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  docs/images/listPersons.png
  docs/images/markAttendance.png
  docs/images/unmarkAttendance.png
Labels: alpha-bug

#191 Add links to commands
  docs/UserGuide.md
Labels: priority.Medium

#279 Fix page break issues in user guide
  docs/UserGuide.md
Labels: priority.High

#268 Fix Developer Guide
  docs/DeveloperGuide.md
  docs/_markbind/layouts/default.md
  docs/addGradeCommand.puml
  docs/diagrams/addGradeCommand.puml
Labels: priority.High
